prometheus:
  enabled: true
  prometheusSpec:
    scrapeInterval: 30s
    retention: 6h
    resources:
      requests:
        memory: "200Mi"
        cpu: "100m"
      limits:
        memory: "400Mi"
        cpu: "300m"
    additionalScrapeConfigs:

      # Your API (already there)
      - job_name: 'acquisitions-api'
        static_configs:
          - targets:
              - 'acquisitions-api-service.acquisitions.svc.cluster.local:80'
        metrics_path: '/metrics'
        scrape_interval: 30s

      - job_name: 'argocd-metrics'
        static_configs:
          - targets:
              - 'argocd-metrics.argocd.svc.cluster.local:8082'
        scrape_interval: 30s

      - job_name: 'argocd-server-metrics'
        static_configs:
          - targets:
              - 'argocd-server-metrics.argocd.svc.cluster.local:8083'
        scrape_interval: 30s

      - job_name: 'argocd-repo-server'
        static_configs:
          - targets:
              - 'argocd-repo-server.argocd.svc.cluster.local:8084'
        scrape_interval: 30s