apiVersion: v1
kind: Service
metadata:
  name: acquisitions-api-service
  namespace: acquisitions
spec:
  selector:
    app: acquisitions-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: NodePort